### ISSUE TITLE
Errors after deleting the app

### ISSUE THREAD

**Issue by Ramdane34** [nextcloud/groupfolders#1020]
After deleting the app, I got this error, when I run this command: files: scan --all 

```
Starting scan for user 94 out of 217 (IvanN)
Exception during scan: A non-numeric value encountered
#0 /var/www/nextcloud/lib/private/Files/Cache/Scanner.php(449): OCA\Files\Command\Scan->exceptionErrorHandler(2, 'A non-numeric v...', '/var/www/nextcl...', 449, Array)
#1 /var/www/nextcloud/lib/private/Files/Cache/Scanner.php(407): OC\Files\Cache\Scanner->handleChildren('files_trashbin/...', true, 3, 53085, true, 0)
#2 /var/www/nextcloud/lib/private/Files/Cache/Scanner.php(410): OC\Files\Cache\Scanner->scanChildren('files_trashbin/...', true, 3, 53085, true)
#3 /var/www/nextcloud/lib/private/Files/Cache/Scanner.php(410): OC\Files\Cache\Scanner->scanChildren('files_trashbin/...', true, 3, 27625, true)
#4 /var/www/nextcloud/lib/private/Files/Cache/Scanner.php(410): OC\Files\Cache\Scanner->scanChildren('files_trashbin', true, 3, 4915, true)
#5 /var/www/nextcloud/lib/private/Files/Cache/Scanner.php(339): OC\Files\Cache\Scanner->scanChildren('', true, 3, 4840, true)
#6 /var/www/nextcloud/lib/private/Files/Utils/Scanner.php(261): OC\Files\Cache\Scanner->scan('', true, 3)
#7 /var/www/nextcloud/apps/files/lib/Command/Scan.php(151): OC\Files\Utils\Scanner->scan('/IvanN', true, NULL)
#8 /var/www/nextcloud/apps/files/lib/Command/Scan.php(207): OCA\Files\Command\Scan->scanFiles('IvanN', '/IvanN', Object(OCA\OCCWeb\Controller\OccOutput), false, true, false)
#9 /var/www/nextcloud/apps/mail/vendor/symfony/console/Command/Command.php(255): OCA\Files\Command\Scan->execute(Object(Symfony\Component\Console\Input\StringInput), Object(OCA\OCCWeb\Controller\Oc
cOutput))
#10 /var/www/nextcloud/core/Command/Base.php(168): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\StringInput), Object(OCA\OCCWeb\Controller\OccOutput))
#11 /var/www/nextcloud/apps/mail/vendor/symfony/console/Application.php(1001): OC\Core\Command\Base->run(Object(Symfony\Component\Console\Input\StringInput), Object(OCA\OCCWeb\Controller\OccOutput)
)
#12 /var/www/nextcloud/apps/mail/vendor/symfony/console/Application.php(271): Symfony\Component\Console\Application->doRunCommand(Object(OCA\Files\Command\Scan), Object(Symfony\Component\Console\In
put\StringInput), Object(OCA\OCCWeb\Controller\OccOutput))
#13 /var/www/nextcloud/apps/mail/vendor/symfony/console/Application.php(147): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\StringInput), Object(OCA\OCCWeb\Con
troller\OccOutput))
#14 /var/www/nextcloud/lib/private/Console/Application.php(214): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\StringInput), Object(OCA\OCCWeb\Controller\OccOutp
ut))
#15 /var/www/nextcloud/apps/occweb/lib/Controller/OccController.php(58): OC\Console\Application->run(Object(Symfony\Component\Console\Input\StringInput), Object(OCA\OCCWeb\Controller\OccOutput))
#16 /var/www/nextcloud/apps/occweb/lib/Controller/OccController.php(75): OCA\OCCWeb\Controller\OccController->run(Object(Symfony\Component\Console\Input\StringInput))
#17 /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(170): OCA\OCCWeb\Controller\OccController->cmd('files:scan --al...')
#18 /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(99): OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\OCCWeb\Controller\OccController), 'cmd')
#19 /var/www/nextcloud/lib/private/AppFramework/App.php(125): OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\OCCWeb\Controller\OccController), 'cmd')
#20 /var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php(47): OC\AppFramework\App::main('OCA\\OCCWeb\\Cont...', 'cmd', Object(OC\AppFramework\DependencyInjection\DIContainer),
 Array)
#21 [internal function: OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)
#22 /var/www/nextcloud/lib/private/Route/Router.php(299): call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)
#23 /var/www/nextcloud/lib/base.php(1008): OC\Route\Router->match('/apps/occweb/cm...')
#24 /var/www/nextcloud/index.php(38): OC::handleRequest()
#25 {main}]
```

**Comment by pierreozoux** [comment]
You mean, you deleted the group folder application, and after ran a filescan and saw this error, correct?
