### ISSUE TITLE
Argument 1 passed to `OCA\GroupFolders\Versions\VersionsBackend::OCA\GroupFolders\Versions\{closure}()` must implement interface `OCP\Files\File`, instance of `OC\Files\Node\Folder`

### ISSUE THREAD

**Issue by ZeikoFr** [nextcloud/groupfolders#1610]
### Steps to reproduce
1. Run sudo -u www-data php occ groupfolders:expire

### Expected behaviour
The command should execute whiout errror
### Actual behaviour
An error is appering :

<details>
<summary>OCC error log</summary>

```
An unhandled exception has been thrown:
TypeError: Argument 1 passed to OCA\GroupFolders\Versions\VersionsBackend::OCA\GroupFolders\Versions\{closure}() must implement interface OCP\Files\File, instance of OC\Files\Node\Folder given in /data/webs/web-4142/nextcloud/apps/groupfolders/lib/Versions/VersionsBackend.php:64
Stack trace:
#0 [internal function]: OCA\GroupFolders\Versions\VersionsBackend->OCA\GroupFolders\Versions\{closure}(Object(OC\Files\Node\Folder))
#1 /data/webs/web-4142/nextcloud/apps/groupfolders/lib/Versions/VersionsBackend.php(78): array_map(Object(Closure), Array)
#2 /data/webs/web-4142/nextcloud/apps/groupfolders/lib/Versions/GroupVersionsExpireManager.php(68): OCA\GroupFolders\Versions\VersionsBackend->getVersionsForFile(Object(OC\User\User), Object(OC\Files\FileInfo))
#3 /data/webs/web-4142/nextcloud/apps/groupfolders/lib/Versions/GroupVersionsExpireManager.php(58): OCA\GroupFolders\Versions\GroupVersionsExpireManager->expireFolder(Array)
#4 /data/webs/web-4142/nextcloud/apps/groupfolders/lib/Command/ExpireGroupVersions.php(60): OCA\GroupFolders\Versions\GroupVersionsExpireManager->expireAll()
#5 /data/webs/web-4142/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OCA\GroupFolders\Command\ExpireGroupVersions->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /data/webs/web-4142/nextcloud/core/Command/Base.php(169): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /data/webs/web-4142/nextcloud/3rdparty/symfony/console/Application.php(1000): OC\Core\Command\Base->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /data/webs/web-4142/nextcloud/3rdparty/symfony/console/Application.php(271): Symfony\Component\Console\Application->doRunCommand(Object(OCA\GroupFolders\Command\ExpireGroupVersions), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /data/webs/web-4142/nextcloud/3rdparty/symfony/console/Application.php(147): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /data/webs/web-4142/nextcloud/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /data/webs/web-4142/nextcloud/console.php(100): OC\Console\Application->run()
#12 /data/webs/web-4142/nextcloud/occ(11): require_once('/data/webs/web-...')
#13 {main}
```
</details>

### Server configuration

**Operating system:**
Debian 10
**Web server:**
Apache/2.4.38
**Database:**
mariadb 10.3.27
**PHP version:**
7.3.27
**Nextcloud version:** (see Nextcloud admin page)
20.0.7
**Group folders version:**
8.2.2
**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated 
**Where did you install Nextcloud from:**
official repo
**Are you using external storage, if yes which one:** local/s3/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/Saml/...
no
#### Web server error log
<details>
<summary>OCC error log</summary>

```
An unhandled exception has been thrown:
TypeError: Argument 1 passed to OCA\GroupFolders\Versions\VersionsBackend::OCA\GroupFolders\Versions\{closure}() must implement interface OCP\Files\File, instance of OC\Files\Node\Folder given in /data/webs/web-4142/nextcloud/apps/groupfolders/lib/Versions/VersionsBackend.php:64
Stack trace:
#0 [internal function]: OCA\GroupFolders\Versions\VersionsBackend->OCA\GroupFolders\Versions\{closure}(Object(OC\Files\Node\Folder))
#1 /data/webs/web-4142/nextcloud/apps/groupfolders/lib/Versions/VersionsBackend.php(78): array_map(Object(Closure), Array)
#2 /data/webs/web-4142/nextcloud/apps/groupfolders/lib/Versions/GroupVersionsExpireManager.php(68): OCA\GroupFolders\Versions\VersionsBackend->getVersionsForFile(Object(OC\User\User), Object(OC\Files\FileInfo))
#3 /data/webs/web-4142/nextcloud/apps/groupfolders/lib/Versions/GroupVersionsExpireManager.php(58): OCA\GroupFolders\Versions\GroupVersionsExpireManager->expireFolder(Array)
#4 /data/webs/web-4142/nextcloud/apps/groupfolders/lib/Command/ExpireGroupVersions.php(60): OCA\GroupFolders\Versions\GroupVersionsExpireManager->expireAll()
#5 /data/webs/web-4142/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OCA\GroupFolders\Command\ExpireGroupVersions->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /data/webs/web-4142/nextcloud/core/Command/Base.php(169): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /data/webs/web-4142/nextcloud/3rdparty/symfony/console/Application.php(1000): OC\Core\Command\Base->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /data/webs/web-4142/nextcloud/3rdparty/symfony/console/Application.php(271): Symfony\Component\Console\Application->doRunCommand(Object(OCA\GroupFolders\Command\ExpireGroupVersions), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /data/webs/web-4142/nextcloud/3rdparty/symfony/console/Application.php(147): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /data/webs/web-4142/nextcloud/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /data/webs/web-4142/nextcloud/console.php(100): OC\Console\Application->run()
#12 /data/webs/web-4142/nextcloud/occ(11): require_once('/data/webs/web-...')
#13 {main}
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"Ssb3jB54SmtV6dgMNDRu","level":1,"time":"August 05, 2021 07:22:10","remoteAddr":"","user":"--","app":"cli","method":"","url":"--","message":"Memcache \\OC\\Memcache\\APCu not available for local cache","userAgent":"--","version":"20.0.7.1"}
{"reqId":"Ssb3jB54SmtV6dgMNDRu","level":1,"time":"August 05, 2021 07:22:10","remoteAddr":"","user":"--","app":"cli","method":"","url":"--","message":"Memcache \\OC\\Memcache\\APCu not available for distributed cache","userAgent":"--","version":"20.0.7.1"}
{"reqId":"Ssb3jB54SmtV6dgMNDRu","level":0,"time":"August 05, 2021 07:22:10","remoteAddr":"","user":"--","app":"groupfolders","method":"","url":"--","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"--","version":"20.0.7.1"}
{"reqId":"Ssb3jB54SmtV6dgMNDRu","level":0,"time":"August 05, 2021 07:22:10","remoteAddr":"","user":"--","app":"files_sharing","method":"","url":"--","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"--","version":"20.0.7.1"}

```
</details>

**Comment by jderegnaucourt** [comment]
Hello @ZeikoFr,
I'm using group folders with following Nextcloud config :
Nextcloud version 22.0.0
ID of application 9906fb25-d117-4d14-a95d-356669569957
package version com.nextcloud.cloudronapp@4.10.0
last update 3 hours ago
Group folders are not working anymore (no more access to folders via interface + no access to the group folders admin panel). It seems it's linked to the last nextcloud version update 3 hours ago -> I'll try to fetch a backup for my users.
Do you know of this is linked to this issue ? Do you have an idea of resolution time ?
Thank you very much.
Regards,
Jules

**Comment by ZeikoFr** [comment]
Hi @jderegnaucourt 

I don't think that this is related at all, has groupfolder has a whole app is working great and I just have a specific problem with the versioning of files.

Regards

**Comment by ZeikoFr** [comment]
This bug is still present on 21.0.3, planning to update to 22 will give more info when updated

**Comment by skjnldsv** [comment]
Fixed 

- https://github.com/nextcloud/groupfolders/pull/3022
- https://github.com/nextcloud/groupfolders/pull/3023
- https://github.com/nextcloud/groupfolders/pull/2995
- https://github.com/nextcloud/groupfolders/pull/2989
