### ISSUE TITLE
Scanning filesystem crash when "Deleted files" app is disabled

### ISSUE THREAD

**Issue by Belse** [nextcloud/groupfolders#1815]
Using latest available nextcloud (23.0.0) and groupfolders (11.1.0).

I run `occ groupfolders:scan 1`

When trashbin (a.k.a Deleted files app) it seems to work.
When trashbin is disabled I get this error:

```
Error: Interface "OCA\Files_Trashbin\Trash\ITrashBackend" not found in /var/www/mysite/apps/groupfolders/lib/Trash/TrashBackend.php:43
Stack trace:
#0 /var/www/mysite/lib/composer/composer/ClassLoader.php(571): include()
#1 /var/www/mysite/lib/composer/composer/ClassLoader.php(428): Composer\Autoload\includeFile('/var/www/mysite....')
#2 /var/www/mysite/apps/groupfolders/lib/AppInfo/Application.php(87): Composer\Autoload\ClassLoader->loadClass('OCA\\GroupFolder...')
#3 /var/www/mysite/lib/private/AppFramework/Utility/SimpleContainer.php(160): OCA\GroupFolders\AppInfo\Application->OCA\GroupFolders\AppInfo\{closure}(Object(OC\AppFramework\DependencyInjection\DIContainer))
#4 /var/www/mysite/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(Pimple\Container))
#5 /var/www/mysite/lib/private/AppFramework/Utility/SimpleContainer.php(127): Pimple\Container->offsetGet('OCA\\GroupFolder...')
#6 /var/www/mysite/lib/private/AppFramework/DependencyInjection/DIContainer.php(457): OC\AppFramework\Utility\SimpleContainer->query('OCA\\GroupFolder...')
#7 /var/www/mysite/lib/private/AppFramework/DependencyInjection/DIContainer.php(435): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback('OCA\\GroupFolder...')
#8 /var/www/mysite/lib/private/AppFramework/Utility/SimpleContainer.php(56): OC\AppFramework\DependencyInjection\DIContainer->query('OCA\\GroupFolder...')
#9 /var/www/mysite/apps/groupfolders/lib/AppInfo/Application.php(110): OC\AppFramework\Utility\SimpleContainer->get('OCA\\GroupFolder...')
#10 /var/www/mysite/lib/private/AppFramework/Utility/SimpleContainer.php(160): OCA\GroupFolders\AppInfo\Application->OCA\GroupFolders\AppInfo\{closure}(Object(OC\AppFramework\DependencyInjection\DIContainer))
#11 /var/www/mysite/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(Pimple\Container))
#12 /var/www/mysite/lib/private/AppFramework/Utility/SimpleContainer.php(127): Pimple\Container->offsetGet('OCA\\GroupFolder...')
#13 /var/www/mysite/lib/private/AppFramework/DependencyInjection/DIContainer.php(457): OC\AppFramework\Utility\SimpleContainer->query('OCA\\GroupFolder...')
#14 /var/www/mysite/lib/private/ServerContainer.php(145): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback('OCA\\GroupFolder...')
#15 /var/www/mysite/lib/private/Console/Application.php(217): OC\ServerContainer->query('OCA\\GroupFolder...')
#16 /var/www/mysite/lib/private/Console/Application.php(128): OC\Console\Application->loadCommandsFromInfoXml(Array)
#17 /var/www/mysite/console.php(98): OC\Console\Application->loadCommands(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /var/www/mysite/occ(11): require_once('/var/www/mysite....')
```

**Comment by CarlSchwan** [comment]
if you could test https://github.com/nextcloud/groupfolders/pull/1849, this would be awesome :)
