### ISSUE TITLE
"Error updating the share: You are not allowed to share [folder name]" when editing shared folder permissions.

### ISSUE THREAD

**Issue by natopwns** [nextcloud/groupfolders#2158]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Create a Group Folder with a sub-folder inside.
2. Share the sub-folder with a user not in the group.
3. Attempt to edit the permissions of the share.

### Expected behaviour
I should be able to edit the permissions (Allow editing, Allow creating, etc.).

### Actual behaviour
I receive an error message notification that reads: "Error updating the share: You are not allowed to share [folder name]". The permissions remain unchanged.

### Server configuration

**Operating system:** Linux 5.4.0-131-generic x86_64

**Web server:** Apache

**Database:** mysql 8.0.30

**PHP version:** 8.0.24

**Nextcloud version:** (see Nextcloud admin page) 24.0.6

**Group folders version:** 12.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** Installed as a Snap originally, so it has updated versions a few times.

**Where did you install Nextcloud from:** Snap

**Are you using external storage, if yes which one:** No

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** LDAP

### Client configuration
**Browser:** Brave Web Browser

**Operating system:** Debian 11 bullseye

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
There is nothing in the Logging page related to this issue.
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
PUT https://share.crossmmg.com/ocs/v2.php/apps/files_sharing/api/v1/shares/2578 404 (Not Found)

ShareRequests.js:111 Error while updating share Error: Request failed with status code 404
    at t.exports (createError.js:16:15)
    at t.exports (settle.js:17:12)
    at XMLHttpRequest.y (xhr.js:66:7)
```
</details>

**Comment by pdelrot-samea** [comment]
Bonjour.
Thanks for the bug report. I just noticed the same problem with a customer.  Nothing to add to the report upper.

Our set-up :  

- docker Nextcloud 27.1.1
- RaspberryPi4 / RasberryPi OS (based on Debian bookworm)

1. Last month we created our server
2. We created a shared group folder for our internal team (RW access).
3. Inside this folder, we created several sub-directories for each projects we have with each different customers to share files, reports...
4. Then we shared these sub-directories to each specific customer people (by invite user)
5. Invite is OK, read access too
6. It is not possible to modify the access to "RW access" despite the option is displayed for each user. The invited users are not able to share with us their files.

The pop-up error message is :

>     You are not allowed to edit incoming shares  
>     Erreur à la mise à jour du partage: You are not allowed to edit incoming shares

The workaround may be to create a group per specific project. This is not the most efficient way to manage the shares, and the directory structure (mostly flat). 

Cordialement,
Pascal
