### ISSUE TITLE
error in consoles with groupfolder 13.0.0 together with NC 25.0.0.18

### ISSUE THREAD

**Issue by GuidoDr** [nextcloud/groupfolders#2162]
these error messages are visible in the developer consoles in Firefox and Edge after the login into Nextcloud.
I did not yet notice that groupfolders were not working fine.
Nevertheless I just wanted to inform about the error message.

**Error message in Firefox:**
```
Uncaught (in promise) ReferenceError: exports is not defined
    37716 getOwnPropertyDescriptor.js:15
    Webpack 17
        o
        22200
        o
        3607
        i
        3351
        i
        exports
        exports
        75925
        o
        75852
        o
        promise callback*
        EventListener.handleEvent*
        <anonymous>
        <anonymous>    
```
    
**Error message in Edge:**
```
index.js:3 
        
       Uncaught (in promise) ReferenceError: exports is not defined
    at 37716 (index.js:3:23)
    at o (bootstrap:19:32)
    at 22200 (index.js:5:16)
    at o (bootstrap:19:32)
    at 3607 (NcAvatar.js:2:140821)
    at i (NcAvatar.js:2:141669)
    at 3351 (NcAvatar.js:2:80061)
    at i (NcAvatar.js:2:141669)
    at NcAvatar.js:2:142357
    at NcAvatar.js:2:142233
```

```
from: webpack:///groupfolders/node_modules/es-abstract/helpers/getOwnPropertyDescriptor.js
from: groupfolders-vendors-node_modules_nextcloud_axios_dist_index_esm_js-node_modules_nextcloud_vue_dist_Compon-fe4846.js
```

**Comment by CarlSchwan** [comment]
Fixed with 13.1.0 that I just released
