### ISSUE TITLE
groupfolders logs show the following...

### ISSUE THREAD

**Issue by TheSpecialist1** [nextcloud/groupfolders#274]
[ERR!] cwd  : /srv/http/owncloud/apps/groupfolders
[ERR!] os   : Linux 4.12.4-1-vfio
[ERR!] argv : "/usr/bin/node" "/usr/bin/tsd" "search" "tooltip"
[ERR!] node : v8.2.1
[ERR!] tsd  : 0.6.5
[ERR!] Error: Cannot find module 'internal/fs'
[ERR!] CODE : MODULE_NOT_FOUND
[ERR!] Cannot find module 'internal/fs'
[ERR!] If you need help, you may report this error at:
    https://github.com/DefinitelyTyped/tsd/issues

[ERR!]
Error: Cannot find module 'internal/fs'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at evalmachine.<anonymous>:40:20
    at Object.<anonymous> (/usr/lib/node_modules/tsd/node_modules/graceful-fs/fs.js:11:1)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)

[ERR!] tsd.json could not be retrieved

[ERR!] .tsdrc could not be retrieved

[ERR!] Please include the following file with any support request:
    /srv/http/owncloud/apps/groupfolders/tsd-debug.log

**Comment by ZeikoFr** [comment]
Hi @TheSpecialist1 is this issue still relevant ?

**Comment by ZeikoFr** [comment]
@juliushaertl I think we can close this one
