### ISSUE TITLE
Advanced permissions tab is not visible

### ISSUE THREAD

**Issue by slaver666** [nextcloud/groupfolders#2747]
### Steps to reproduce
1. Open Details of the created Group folder
2. Open Sharing tab

### Expected behaviour
You should see users with advanced permissions as you previously set it up in Group Folders list for this folder

### Actual behaviour
No Advanced permissions visible

### Server configuration

**Operating system:**
Ubuntu 22.04.3 LTS

**Web server:**
Nginx 1.25.3

**Database:**
PostgreSQL 15.5

**PHP version:**
8.2

**Nextcloud version:** (see Nextcloud admin page)
28.0.1

**Group folders version:**
16.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
updated from NC 27

**Where did you install Nextcloud from:**
Community zip package from official site

**Are you using external storage, if yes which one:** local/s3/smb/sftp/...
No

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/Saml/...
no

### Client configuration
**Browser:**
Google Chrome, Brave, Firefox

**Operating system:**
Ubuntu Linux, Windows 10

#### Web server error log
<details>
<summary>Web server error log</summary>

```
2024/01/12 17:12:46 [error] 291724#291724: *9070 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Class OCA\GroupFolders\Helper\LazyFolder contains 2 abstract methods and must therefore be declared abstract or implement the remaining methods (OCP\Files\Folder::searchBySystemTag, OCP\Files\FileInfo::getMetadata) in /var/www/nextcloud/apps/groupfolders/lib/Helper/LazyFolder.php on line 32" while reading response header from upstream, client: 172.19.19.3, server: cloud.kit-electro.ru, request: "PROPFIND /remote.php/dav/files/vyacheslav.bakhur/ HTTP/1.1", upstream: "fastcgi://unix:/run/php/php8.2-fpm-www2.sock:", host: "cloud.kit-electro.ru"
2024/01/12 17:13:02 [error] 291724#291724: *9158 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Class OCA\GroupFolders\Helper\LazyFolder contains 2 abstract methods and must therefore be declared abstract or implement the remaining methods (OCP\Files\Folder::searchBySystemTag, OCP\Files\FileInfo::getMetadata) in /var/www/nextcloud/apps/groupfolders/lib/Helper/LazyFolder.php on line 32" while reading response header from upstream, client: 5.18.228.198, server: cloud.kit-electro.ru, request: "PROPFIND /remote.php/dav/files/tatyana.poloskina/ HTTP/1.1", upstream: "fastcgi://unix:/run/php/php8.2-fpm-www2.sock:", host: "cloud.kit-electro.ru"
2024/01/12 17:13:06 [error] 291724#291724: *9158 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Class OCA\GroupFolders\Helper\LazyFolder contains 2 abstract methods and must therefore be declared abstract or implement the remaining methods (OCP\Files\Folder::searchBySystemTag, OCP\Files\FileInfo::getMetadata) in /var/www/nextcloud/apps/groupfolders/lib/Helper/LazyFolder.php on line 32" while reading response header from upstream, client: 172.19.19.3, server: cloud.kit-electro.ru, request: "GET /apps/files/ HTTP/1.1", upstream: "fastcgi://unix:/run/php/php8.2-fpm-www2.sock:", host: "cloud.kit-electro.ru"

```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"v4JdJb2uyOiE5mDk5ogU","level":3,"time":"2024-01-12T15:00:22+00:00","remoteAddr":"85.249.18.99","user":"sergey.suetin","app":"webdav","method":"PROPFIND","url":"/remote.php/dav/files/sergey.suetin/%D0%97%D0%B0%D0%BC%D0%B5%D1%82%D0%BA%D0%B8","message":"No read permissions. This might be caused by files_accesscontrol, check your configured rules","userAgent":"Mozilla/5.0 (Windows) mirall/3.11.0stable-Win64 (build 20231211) (Nextcloud, windows-10.0.19045 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"28.0.1.1","exception":{"Exception":"OCA\\DAV\\Connector\\Sabre\\Exception\\Forbidden","Message":"No read permissions. This might be caused by files_accesscontrol, check your configured rules","Code":0,"Trace":[{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Tree.php","line":206,"function":"getChildren","class":"OCA\\DAV\\Connector\\Sabre\\Directory","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":900,"function":"getChildren","class":"Sabre\\DAV\\Tree","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":982,"function":"generatePathNodes","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":1662,"function":"getPropertiesIteratorForPath","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":1647,"function":"writeMultiStatus","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":346,"function":"generateMultiStatus","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"httpPropFind","class":"Sabre\\DAV\\CorePlugin","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":472,"function":"emit","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":253,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":321,"function":"start","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/apps/dav/lib/Server.php","line":370,"function":"exec","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/remote.php","line":172,"args":["/var/www/nextcloud/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/var/www/nextcloud/apps/dav/lib/Connector/Sabre/Directory.php","Line":256,"message":"No read permissions. This might be caused by files_accesscontrol, check your configured rules","exception":{},"CustomMessage":"No read permissions. This might be caused by files_accesscontrol, check your configured rules"}}
{"reqId":"d0L9swrFfaVFYPD4SowE","level":3,"time":"2024-01-12T15:01:23+00:00","remoteAddr":"85.249.18.99","user":"sergey.suetin","app":"webdav","method":"PROPFIND","url":"/remote.php/dav/files/sergey.suetin/%D0%97%D0%B0%D0%BC%D0%B5%D1%82%D0%BA%D0%B8","message":"No read permissions. This might be caused by files_accesscontrol, check your configured rules","userAgent":"Mozilla/5.0 (Windows) mirall/3.11.0stable-Win64 (build 20231211) (Nextcloud, windows-10.0.19045 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"28.0.1.1","exception":{"Exception":"OCA\\DAV\\Connector\\Sabre\\Exception\\Forbidden","Message":"No read permissions. This might be caused by files_accesscontrol, check your configured rules","Code":0,"Trace":[{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Tree.php","line":206,"function":"getChildren","class":"OCA\\DAV\\Connector\\Sabre\\Directory","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":900,"function":"getChildren","class":"Sabre\\DAV\\Tree","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":982,"function":"generatePathNodes","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":1662,"function":"getPropertiesIteratorForPath","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":1647,"function":"writeMultiStatus","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":346,"function":"generateMultiStatus","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"httpPropFind","class":"Sabre\\DAV\\CorePlugin","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":472,"function":"emit","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":253,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":321,"function":"start","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/apps/dav/lib/Server.php","line":370,"function":"exec","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/remote.php","line":172,"args":["/var/www/nextcloud/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/var/www/nextcloud/apps/dav/lib/Connector/Sabre/Directory.php","Line":256,"message":"No read permissions. This might be caused by files_accesscontrol, check your c
![02](https://github.com/nextcloud/groupfolders/assets/63472976/9cf03e1d-90c0-49c0-8ca2-6c3eb54248bf)
![01](https://github.com/nextcloud/groupfolders/assets/63472976/ed33d75b-7130-4043-a577-95fbbd347da7)
onfigured rules","exception":{},"CustomMessage":"No read permissions. This might be caused by files_accesscontrol, check your configured rules"}}

```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
groupfolders-vendors-node_modules_nextcloud_vue_dist_Components_NcActionRadio_js-node_modules_nextcloud_vu-eb9638.js?v=7bdb2790ad3553ebf0eb:2 TypeError: Cannot read properties of undefined (reading 'getFileInfo')
    at e.value (groupfolders-files.js?v=0fc4b768-58:2:4988)
    at o.loadAcls (groupfolders-sharing.js?v=1159a50aa9d838a68f10:2:5320)
    at o.beforeMount (groupfolders-sharing.js?v=1159a50aa9d838a68f10:2:5179)
    at Cn (groupfolders-vendors-node_modules_nextcloud_vue_dist_Components_NcActionRadio_js-node_modules_nextcloud_vu-eb9638.js?v=7bdb2790ad3553ebf0eb:2:2497833)
    at Aa (groupfolders-vendors-node_modules_nextcloud_vue_dist_Components_NcActionRadio_js-node_modules_nextcloud_vu-eb9638.js?v=7bdb2790ad3553ebf0eb:2:2503695)
    at e (groupfolders-vendors-node_modules_nextcloud_vue_dist_Components_NcActionRadio_js-node_modules_nextcloud_vu-eb9638.js?v=7bdb2790ad3553ebf0eb:2:2550839)
    at ui.$mount (groupfolders-vendors-node_modules_nextcloud_vue_dist_Components_NcActionRadio_js-node_modules_nextcloud_vu-eb9638.js?v=7bdb2790ad3553ebf0eb:2:2551116)
    at init (vue.runtime.esm.js:4411:19)
    at vue.runtime.esm.js:6571:17
    at h (vue.runtime.esm.js:6525:13)```
</details>

**Comment by slaver666** [comment]
![01](https://github.com/nextcloud/groupfolders/assets/63472976/cb7ec748-c9f0-44df-ba3e-40e750a913bb)
![02](https://github.com/nextcloud/groupfolders/assets/63472976/00ac7098-3d73-4996-a9f6-a94ded0a4e19)
