### ISSUE TITLE
Error: Interface "OCA\Files_Versions\Versions\INeedSyncVersionBackend" not found in /var/www/html/custom_apps/groupfolders/lib/Versions/VersionsBackend.php:46

### ISSUE THREAD

**Issue by MrNunu** [nextcloud/groupfolders#2843]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Installed Nextcloud AIO 4.x, Nextcloud 25.x in Feb 2023 and probably GroupFolder 14.0. 
2. Keep updating both Nextcloud and GroupFolder, almost never skipping versions. 

### Expected behaviour
No error logs

### Actual behaviour
Seems to be getting some version of the issues that have been reported in #2566 or #2548, but I don't have problems with either cron or occ command. Both work and as far as I can tell, everything actually works. But I'm getting a constant flood of error logs like this:

```
[no app in context] Warning: AppManger::checkAppForUser - can't decode group IDs: An unhandled exception has been thrown:
Error: Interface "OCA\Files_Versions\Versions\INeedSyncVersionBackend" not found in /var/www/html/custom_apps/groupfolders/lib/Versions/VersionsBackend.php:46
Stack trace:
#0 /var/www/html/lib/composer/composer/ClassLoader.php(582): include()
#1 /var/www/html/lib/composer/composer/ClassLoader.php(433): Composer\Autoload\{closure}('/var/www/html/c...')
#2 /var/www/html/custom_apps/groupfolders/lib/AppInfo/Application.php(138): Composer\Autoload\ClassLoader->loadClass('OCA\\GroupFolder...')
#3 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(171): OCA\GroupFolders\AppInfo\Application->OCA\GroupFolders\AppInfo\{closure}(Object(OC\AppFramework\DependencyInjection\DIContainer))
#4 /var/www/html/3rdparty/pimple/pimple/src/Pimple/Container.php(122): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(Pimple\Container))
#5 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(138): Pimple\Container->offsetGet('OCA\\GroupFolder...')
#6 /var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php(488): OC\AppFramework\Utility\SimpleContainer->query('OCA\\GroupFolder...')
#7 /var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php(466): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback('OCA\\GroupFolder...')
#8 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(97): OC\AppFramework\DependencyInjection\DIContainer->query('OCA\\GroupFolder...', true)
#9 [internal function]: OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(ReflectionParameter))
#10 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(116): array_map(Object(Closure), Array)
#11 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(124): OC\AppFramework\Utility\SimpleContainer->buildClass(Object(ReflectionClass))
#12 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(142): OC\AppFramework\Utility\SimpleContainer->resolve('OCA\\GroupFolder...')
#13 /var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php(494): OC\AppFramework\Utility\SimpleContainer->query('OCA\\GroupFolder...')
#14 /var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php(466): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback('OCA\\GroupFolder...')
#15 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(65): OC\AppFramework\DependencyInjection\DIContainer->query('OCA\\GroupFolder...')
#16 /var/www/html/custom_apps/groupfolders/lib/AppInfo/Application.php(158): OC\AppFramework\Utility\SimpleContainer->get('OCA\\GroupFolder...')
#17 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(171): OCA\GroupFolders\AppInfo\Application->OCA\GroupFolders\AppInfo\{closure}(Object(OC\AppFramework\DependencyInjection\DIContainer))
#18 /var/www/html/3rdparty/pimple/pimple/src/Pimple/Container.php(122): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(Pimple\Container))
#19 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(138): Pimple\Container->offsetGet('OCA\\GroupFolder...')
#20 /var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php(488): OC\AppFramework\Utility\SimpleContainer->query('OCA\\GroupFolder...')
#21 /var/www/html/lib/private/ServerContainer.php(155): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback('OCA\\GroupFolder...')
#22 /var/www/html/lib/private/Console/Application.php(217): OC\ServerContainer->query('OCA\\GroupFolder...')
#23 /var/www/html/lib/private/Console/Application.php(131): OC\Console\Application->loadCommandsFromInfoXml(Array)
#24 /var/www/html/console.php(99): OC\Console\Application->loadCommands(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 /var/www/html/occ(11): require_once('/var/www/html/c...')
#26 {main} - json error code: 4
```

I tried disabling the application and the logs continue. I tried deleting the application and the logs continue. And of course I reinstalled and the logs continue. 

### Server configuration

**Operating system:** Ubuntu 23.04

**Web server:** Apache/2.4.58 (Unix) (Included with AIO)

**Database:** PostgreSQL 15.6 (Included with AIO)

**PHP version:** 8.1.27 (Included with AIO)

**Nextcloud version:** (see Nextcloud admin page) 28.0.3

**Group folders version:** 16.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:** Update from Nextcloud 25.x

**Where did you install Nextcloud from:** Nextcloud AIO Docker Compose

**Are you using external storage, if yes which one:** smb, but not used in Group Folders

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 123.0

**Operating system:** Windows 11

#### Web server error log
<details>
<summary>Web server error log</summary>

Unsure where to get those in AIO
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
[no app in context] Warning: AppManger::checkAppForUser - can't decode group IDs: An unhandled exception has been thrown:
Error: Interface "OCA\Files_Versions\Versions\INeedSyncVersionBackend" not found in /var/www/html/custom_apps/groupfolders/lib/Versions/VersionsBackend.php:46
Stack trace:
#0 /var/www/html/lib/composer/composer/ClassLoader.php(582): include()
#1 /var/www/html/lib/composer/composer/ClassLoader.php(433): Composer\Autoload\{closure}('/var/www/html/c...')
#2 /var/www/html/custom_apps/groupfolders/lib/AppInfo/Application.php(138): Composer\Autoload\ClassLoader->loadClass('OCA\\GroupFolder...')
#3 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(171): OCA\GroupFolders\AppInfo\Application->OCA\GroupFolders\AppInfo\{closure}(Object(OC\AppFramework\DependencyInjection\DIContainer))
#4 /var/www/html/3rdparty/pimple/pimple/src/Pimple/Container.php(122): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(Pimple\Container))
#5 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(138): Pimple\Container->offsetGet('OCA\\GroupFolder...')
#6 /var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php(488): OC\AppFramework\Utility\SimpleContainer->query('OCA\\GroupFolder...')
#7 /var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php(466): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback('OCA\\GroupFolder...')
#8 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(97): OC\AppFramework\DependencyInjection\DIContainer->query('OCA\\GroupFolder...', true)
#9 [internal function]: OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(ReflectionParameter))
#10 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(116): array_map(Object(Closure), Array)
#11 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(124): OC\AppFramework\Utility\SimpleContainer->buildClass(Object(ReflectionClass))
#12 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(142): OC\AppFramework\Utility\SimpleContainer->resolve('OCA\\GroupFolder...')
#13 /var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php(494): OC\AppFramework\Utility\SimpleContainer->query('OCA\\GroupFolder...')
#14 /var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php(466): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback('OCA\\GroupFolder...')
#15 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(65): OC\AppFramework\DependencyInjection\DIContainer->query('OCA\\GroupFolder...')
#16 /var/www/html/custom_apps/groupfolders/lib/AppInfo/Application.php(158): OC\AppFramework\Utility\SimpleContainer->get('OCA\\GroupFolder...')
#17 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(171): OCA\GroupFolders\AppInfo\Application->OCA\GroupFolders\AppInfo\{closure}(Object(OC\AppFramework\DependencyInjection\DIContainer))
#18 /var/www/html/3rdparty/pimple/pimple/src/Pimple/Container.php(122): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(Pimple\Container))
#19 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(138): Pimple\Container->offsetGet('OCA\\GroupFolder...')
#20 /var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php(488): OC\AppFramework\Utility\SimpleContainer->query('OCA\\GroupFolder...')
#21 /var/www/html/lib/private/ServerContainer.php(155): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback('OCA\\GroupFolder...')
#22 /var/www/html/lib/private/Console/Application.php(217): OC\ServerContainer->query('OCA\\GroupFolder...')
#23 /var/www/html/lib/private/Console/Application.php(131): OC\Console\Application->loadCommandsFromInfoXml(Array)
#24 /var/www/html/console.php(99): OC\Console\Application->loadCommands(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 /var/www/html/occ(11): require_once('/var/www/html/c...')
#26 {main} - json error code: 4
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by Kryptopirat** [comment]
I also have this problem, but I with the normal installation.

**Comment by MrNunu** [comment]
Is there anything else I can provide as far as logs, files, configs or anything else that could help clarify this problem?

**Comment by joshtrichards** [comment]
https://github.com/nextcloud/all-in-one/issues/4806#issuecomment-2160283858

Also the error messaging is improved a bit now too (though it really should never occur; it was a freak bug in AIO that brought it out)

https://github.com/nextcloud/server/pull/45737

**Comment by joshtrichards** [comment]
Do you have the *Versions* app enabled?

**Comment by provokateurin** [comment]
Yeah, there seems to be no check if the files_versions app is enabled. If it is disabled the class is not available so VersionsBackend can not be instantiated.
