### ISSUE TITLE
3.0.1 upgrade breaks NextCloud 15

### ISSUE THREAD

**Issue by fasterit** [nextcloud/groupfolders#417]
Trying to fix #395 you managed to break occ again. And the UI, too, this time.
Consider testing your code on php 7.0, too.

Nextcloud 15.0.7, php 7.0.33 (Debian stable aka Stretch 9.9)

Same issue with the [ ..., ... ] = ...

```
# occ 
An unhandled exception has been thrown:
ParseError: syntax error, unexpected '=' in /var/www/cluster4711/apps/groupfolders/lib/Trash/TrashBackend.php:134
Stack trace:
#0 /var/www/cluster4711/lib/composer/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/var/www/cluster-...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('OCA\\GroupFolder...')
#2 /var/www/cluster4711/apps/groupfolders/lib/AppInfo/Application.php(67): spl_autoload_call('OCA\\GroupFolder...')
#3 /var/www/cluster4711/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OCA\GroupFolders\AppInfo\Application->OCA\GroupFolders\AppInfo\{closure}(Object(OC\AppFramework\DependencyInjection\DIContainer))
#4 /var/www/cluster4711/lib/private/AppFramework/Utility/SimpleContainer.php(117): Pimple\Container->offsetGet('OCA\\GroupFolder...')
#5 /var/www/cluster4711/lib/private/AppFramework/DependencyInjection/DIContainer.php(419): OC\AppFramework\Utility\SimpleContainer->query('OCA\\GroupFolder...')
#6 /var/www/cluster4711/lib/private/ServerContainer.php(116): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback('OCA\\GroupFolder...')
#7 /var/www/cluster4711/apps/files_trashbin/lib/AppInfo/Application.php(90): OC\ServerContainer->query('OCA\\GroupFolder...')
#8 /var/www/cluster4711/apps/files_trashbin/lib/AppInfo/Application.php(72): OCA\Files_Trashbin\AppInfo\Application->registerTrashBackends()
#9 /var/www/cluster4711/lib/private/ServerContainer.php(89): OCA\Files_Trashbin\AppInfo\Application->__construct()
#10 /var/www/cluster4711/lib/private/ServerContainer.php(115): OC\ServerContainer->getAppContainer('files_trashbin', 'Files_Trashbin')
#11 /var/www/cluster4711/apps/files_trashbin/lib/Storage.php(201): OC\ServerContainer->query('OCA\\Files_Trash...')
#12 /var/www/cluster4711/lib/private/Files/Storage/StorageFactory.php(101): OCA\Files_Trashbin\Storage::OCA\Files_Trashbin\{closure}('/', Object(OC\Files\Storage\Local), Object(OC\Files\Mount\MountPoint))
#13 /var/www/cluster4711/lib/private/Files/Mount/MountPoint.php(148): OC\Files\Storage\StorageFactory->wrap(Object(OC\Files\Mount\MountPoint), Object(OC\Files\Storage\Local))
#14 /var/www/cluster4711/lib/private/Files/Mount/MountPoint.php(172): OC\Files\Mount\MountPoint->createStorage()
#15 /var/www/cluster4711/lib/private/Files/View.php(1373): OC\Files\Mount\MountPoint->getStorage()
#16 /var/www/cluster4711/lib/private/Files/Node/Root.php(198): OC\Files\View->getFileInfo('/appdata_ocnmnv...')
#17 [internal function]: OC\Files\Node\Root->get('/appdata_ocnmnv...')
#18 /var/www/cluster4711/lib/private/Files/Node/LazyRoot.php(64): call_user_func_array(Array, Array)
#19 /var/www/cluster4711/lib/private/Files/Node/LazyRoot.php(141): OC\Files\Node\LazyRoot->__call('get', Array)
#20 /var/www/cluster4711/lib/private/Files/AppData/AppData.php(81): OC\Files\Node\LazyRoot->get('appdata_ocnmnvs...')
#21 /var/www/cluster4711/lib/private/Files/AppData/AppData.php(107): OC\Files\AppData\AppData->getAppDataFolder()
#22 /var/www/cluster4711/lib/private/Template/IconsCacher.php(78): OC\Files\AppData\AppData->getFolder('icons')
#23 [internal function]: OC\Template\IconsCacher->__construct(Object(OC\Log), Object(OC\Files\AppData\Factory), Object(OC\URLGenerator), Object(OC\AppFramework\Utility\TimeFactory))
#24 /var/www/cluster4711/lib/private/AppFramework/Utility/SimpleContainer.php(81): ReflectionClass->newInstanceArgs(Array)
#25 /var/www/cluster4711/lib/private/AppFramework/Utility/SimpleContainer.php(98): OC\AppFramework\Utility\SimpleContainer->buildClass(Object(ReflectionClass))
#26 /var/www/cluster4711/lib/private/AppFramework/Utility/SimpleContainer.php(119): OC\AppFramework\Utility\SimpleContainer->resolve('OC\\Template\\Ico...')
#27 /var/www/cluster4711/lib/private/ServerContainer.php(132): OC\AppFramework\Utility\SimpleContainer->query('OC\\Template\\Ico...')
#28 /var/www/cluster4711/lib/private/Server.php(980): OC\ServerContainer->query('OC\\Template\\Ico...')
#29 /var/www/cluster4711/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\Server->OC\{closure}(Object(OC\Server))
#30 /var/www/cluster4711/lib/private/AppFramework/Utility/SimpleContainer.php(117): Pimple\Container->offsetGet('OC\\Template\\SCS...')
#31 /var/www/cluster4711/lib/private/ServerContainer.php(132): OC\AppFramework\Utility\SimpleContainer->query('OC\\Template\\SCS...')
#32 /var/www/cluster4711/lib/private/Repair.php(145): OC\ServerContainer->query('OC\\Template\\SCS...')
#33 /var/www/cluster4711/core/register_command.php(143): OC\Repair::getRepairSteps()
#34 /var/www/cluster4711/lib/private/Console/Application.php(118): require_once('/var/www/cluster-...')
#35 /var/www/cluster4711/console.php(95): OC\Console\Application->loadCommands(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#36 /var/www/cluster4711/occ(11): require_once('/var/www/cluster-...')
#37 {main}

```

**Comment by supremesyntax** [comment]
i can't disable groupfolders using the occ command. i am getting the error in the initial post.

is there another way to disable it ?

**Comment by scharel** [comment]
> i can't disable groupfolders using the occ command. i am getting the error in the initial post.
> 
> is there another way to disable it ?

@supremesyntax you can manually edit the file as shown [here](https://github.com/nextcloud/groupfolders/commit/8951bb1f64a7e094f6dffc8157c66cd2f0c178e8)

**Comment by supremesyntax** [comment]
@scharel thx! users were complaining so i manually downloaded the tar.gz an copied the files. the chown them for www-data and had to run "occ upgrade"
